name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Verify pnpm
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        working-directory: ./apps/server
        run: pnpm test
